print("why dont skeletons fight each other")
input("")
print("because they dont have the guts")
input("")
print("what do you call a belt full of watches")
input("")
print("a waist of time!")
input("")
print("i tired to catch some fog yesterday")
input("")
print("i mist it")
input("")
