name=input("What is your name? ")
print("I love that name!!!")
input("")
personality=input("now give me a personality trait ")
print("Ooooo great choice")
input("")
place=input("now give me a place ")
print("I love it there")
input("")
animal=input("Name any animal ")
print("hey thats my favorite animal!")
input("")
verb=input("now give me a verb ending in ing ")
print("wow great choice")
input("")
answer2=input("are you ready to see your story? ")
if answer2 == "yes" or answer2 == "Yes" or answer2 == " yes" or answer2 == " Yes":
    print("lets do it!")
else:
    print("to bad we are doing it anyways")
input("")
print(f"once there was an elephant named {name}")
input("")
print(f"{name} was very {personality}")
input("")
print(f"one day {name} went to {place}")
input("")
print(f"At {place} {name} ran into a {animal}")
input("")
print(f"the {animal} ended up {verb} all the way back home")
input("")
print("the end thank you!") 